require("plugins.colorschemes.onedark")

require("plugins.dressing")
require("plugins.lsp-config")
require("plugins.mason")
require("plugins.nvim-cmp")
require("plugins.conform")
require("plugins.lazydev")
require("plugins.roslyn")
require("plugins.lazygit")
require("plugins.nvim-dap")
require("plugins.nvim-dap-ui")
require("plugins.nvim-tree")
require("plugins.nvim-treesitter")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.vim-visual-multi")
